name: flutter_naurt_sdk
description: >-
  Flutter plugin of the Naurt SDK for Android and iOS.
  Naurt is Location optimisation software improving your accuracy and precision 
  by 40% to 90%. Naurt is a plug-and-play software toolkit for high-precision tracking. 
  Works anywhere in the world, both indoors and outdoors.
version: 1.0.0
homepage: https://www.naurt.com
documentation:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.naurt.flutter_naurt_sdk
        pluginClass: FlutterNaurtSdk
      ios:
        pluginClass: FlutterNaurtSdk
